### ISSUE TITLE
Incorrect callback_user_sessions_url

### ISSUE THREAD

**Issue by almeric** [gitlabhq/gitlab-ci#530]
I've just upgrade Gitlab-ci to 5.4 ( & gitlab to 7.7) and I'm having problems getting authentication to work.  
  
Our situation:  
We have both gitlab & gitlab-ci running on an internal dev server:  
- gitlab.dev.lan
- git-ci.dev.lan

Both are behind apache using mod_proxy.  
  
When I try to login, however, I get the following error in gitlab: `The redirect uri included is not valid.`. This is because the redirect_url GET variable uses `http://` instead of `https://`.  

If I go to the OAuth help page at `https://git-ci.dev.lan/help/oauth2` it also mentions http instead of https:  
`In the GitLab admin area under OAuth applications create a new entry. The redirect url should be http://git-ci.dev.lan/user_sessions/callback`  
  
My application.yml:

```yaml
defaults: &defaults
  gitlab_server:
    url: 'http://gitlab.dev.lan/' # Replace with your gitlab server url
    app_id: 'id-from-gitlab'
    app_secret: 'secret-from-gitlab'

  ## Gitlab CI settings
  gitlab_ci:
    ## Web server settings
    host: localhost
    port: 80
    https: true
```

Any ideas?
