### ISSUE TITLE
7-12-stable gitlab_ci_yaml_processor.rb error

### ISSUE THREAD

**Issue by azt3k** [gitlabhq/gitlab-ci#604]
I get this error when I test a project in the `7-12-stable` branch

````bash
NoMethodError (undefined method `map' for nil:NilClass):
  lib/gitlab_ci_yaml_processor.rb:38:in `builds'
  lib/gitlab_ci_yaml_processor.rb:30:in `builds_for_ref'
  lib/gitlab_ci_yaml_processor.rb:34:in `any_jobs?'
  app/services/create_commit_service.rb:20:in `execute'
  app/controllers/projects_controller.rb:90:in `build'
````
project `.gitlab-ci.yml` file
````yaml
# http://doc.gitlab.com/ci/builds_configuration/README.html
before_script:
  - echo "test"
specs:
  script: bash bin/test-ci
````
