### ISSUE TITLE
7-12-stable - Fails to read `.gitlab-ci.yml` file, uses database field instead that is inaccessible via UI

### ISSUE THREAD

**Issue by azt3k** [gitlabhq/gitlab-ci#605]
## Linter output

````txt
 Status: syntax is correct 
````

## Output on commit

````txt
Found errors in your .gitlab-ci.yml:
    YAML should be a hash
````

## `.gitlab-ci.yml` that should be used, but isn't

````yaml
before_script:
  - bash bin/test-setup

SapphireTest:
  script:
    - bash public/framework/sake dev/tests/all
  tags:
    - php
    - silverstripe
    - sqlite
````
## Actual data that is used

comes from db field `projects.generated_yaml_config`

````yaml
# This file is generated by GitLab CI {}
````
