### ISSUE TITLE
Not running tasks

### ISSUE THREAD

**Issue by bweston92** [gitlabhq/gitlab-ci#606]
I have this in my `.gitlab-ci.yml` it runs the `before_script` but not `phpmd` or `phpspec` tasks.

```
before_script:
- "composer install"

phpmd:
  test: "phpmd app text phpmd.xml"
  tags:
    - "phpmd"

phpspec:
  test: "phpspec run --no-code-generation"
  tags:
    - "phpspec"
```

I followed this guide https://about.gitlab.com/2015/06/08/implementing-gitlab-ci-dot-yml/
