### ISSUE TITLE
Getting message - Please define at least one job

### ISSUE THREAD

**Issue by gintsgints** [gitlabhq/gitlab-ci#630]
I try different ways of configure jobs in yml file. Last I try is:

```
stages:
  - ver
  - init
  - build
  - test
  - deploy

ver:
  stage: ver
  script:
    - python -V
    - node --version
    - grunt --version
    - bower --version

job:
  stage: init
  script:
    - npm cache clean
    - rm -rf node_modules
    - npm install

job:
  stage: init
  script:
    - bower install

job:
  stage: test
  script:
    - grunt jshint:server --force
    - grunt test
  only:
    - develop

job:
  stage: build
  script:
    - grunt build

job:
  stage: deploy
  script:
    - grunt ssh_deploy:prod --keyfile=/var/lib/jenkins/.ssh/id_rsa
  only:
    - master
```

and I get message - Please define at least one job.
