### ISSUE TITLE
It is possible configure the field only so only: tags event and master branch or other branch?

### ISSUE THREAD

**Issue by thepianist2** [gitlabhq/gitlab-ci#639]
It is possible configure the field only so ?

  only:
    - tags & master

i need execute the stage only on the events on master and tags.

```yml
stages:
  - primera

job1:
  stage: job1
  script:
    - echo job1
  only:
    - tags & master
```

Sorry for my poor English.

**Comment by ayufan** [comment]
Yes:
```

job1:
  stage: job1
  script:
    - echo job1
  only:
    - tags
    - master
```

**Comment by thepianist2** [comment]
Yes, but the problem is that the way you say runs when making the push on the master branch and when to raise the tag , what I want , it is in the master branch and the together tag event , not separately.

**Comment by ayufan** [comment]
You can check that in your build script. That a tag your are building is the `master`.

**Comment by thepianist2** [comment]
Yes, the tag your are building is the master, but:

What I want , example :

git commit
git push origin master
// not build
git tag -a 0.1.0
git push origin --tag
// build

Only at this point should the build , because it is in the master branch and do a push of tags .

**Comment by JoshKCarroll** [comment]
Anyone figured out a workaround for this? I'm trying to do it too and can't figure out a good workaround. Thanks!

**Comment by ZJvandeWeg** [comment]
@JoshKCarroll This is not supported at this time.

But if you're ok with triggering a build on every tag pushed, you could check if the SHA of the tag is in master, if not, exit 1 (thus the build passes), else run other tests.

Could this be the workaround which you are looking for?

**Comment by JoshKCarroll** [comment]
@ZJvandeWeg nice idea, thank you! I will see what I can come up with.

I did figure out a fix to make sure builds in forks would be separated properly (and make code more portable across projects), although it requires dependency on format of $CI_PROJECT_DIR

```

**Comment by JoshKCarroll** [comment]
@ZJvandeWeg do you have suggestion for what command to check this or get the branches containing the ref of the tag from CI? All discussion I find online points to `git branch --contains` but since CI is running with detached head it doesn't seem to work. And `$ci_build_ref_name` is the tag name rather than the branch in a tag build.

E.g. output when I try to check this in CI for a tag build (tag name `fake`):
```
$ echo $CI_BUILD_REF_NAME
fake
$ echo $CI_BUILD_REF
b641eda89c7eb5602e1ea1845300957c7c15c657
$ git branch --contains $CI_BUILD_TAG
* (detached from b641eda)
$ git branch --contains $CI_BUILD_REF
* (detached from b641eda)
```

**Comment by ZJvandeWeg** [comment]
Im not sure about this, as I haven't worked on the internals or read this part of the source. But what you could try is to enable `git clone` instead of `git fetch`. This can be switched in your project settings.

Maybe good to know too; there will be an option to set [the depth of a fetch](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/316).

**Comment by JoshKCarroll** [comment]
Cool, I tried that and it didn't seem to change the output from above commands. No worries. Good to know about the depth option. If we have problems enforcing this with process, maybe we can flip to just using triggers for build and push.

I agree with original poster, the ideal solution would be to support "AND"ing criteria together in only/except.
Thank you!!

**Comment by alleus** [comment]
Did you find any way to figure out the branch name @JoshKCarroll?

**Comment by JoshKCarroll** [comment]
Nope, have not.

**Comment by alleus** [comment]
I _somewhat_ solved this now. Basically, I noticed that `git branch --contains $CI_BUILD_REF` does indeed return data, but only if the reference is found on the `master` branch.

So now I have a config that:

* For regular commits, not on `develop` or `master`, will build and test my code
* For tags, conforming to [semver.org](http://semver.org), on the `master` branch, will deploy to production
* For tags, conforming to [semver.org](http://semver.org), on any other branch, will deploy to stage

```Build:
  script:
    - echo "Build and test code without deploy"
  stage: build
  only:
    - branches
  except:
    - develop
    - master
Release:
  script:
    - grep -q "master" <<< $(git branch --contains $CI_BUILD_REF) && echo "Build release and deploy to production" || echo "Build release and deploy to stage"
  stage: deploy
  only:
    - /^v?[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-.]+)?$/```

**Comment by jimmy0251** [comment]
This should work:
```
stages:
  - primera

job1:
  stage: job1
  script:
    - echo job1
  only:
    - tags
  only:
    - master
```

**Comment by alleus** [comment]
@jimmy0251  Do you mean that this has been changed since we got the answer from ZJvandeWeg?

> This is not supported at this time

**Comment by jimmy0251** [comment]
@alleus I'm not sure about when it's implemented, but given code works fine for me. The trick is to create "only" tag two times instead of providing two conditions in one "only" tag.

**Comment by windinn** [comment]
@jimmy0251 It's not work for me. I upgraded my gitlab to gitlab/gitlab-ce:8.13.0-ce.0, still not work.

**Comment by leondeng** [comment]
Need this feature as well, definitely.

**Comment by carusology** [comment]
The solution given by @jimmy0251 no longer works on gitlab.com. We're once again getting untagged commits to master triggering the build.

**Comment by AyumuKasuga** [comment]
We really need this feature!

**Comment by plitex** [comment]
It's not working for me @alleus. This is what I see when tagging a version in master branch:

```bash
Checking out 795db067 as v1.0.0...
$ echo $CI_BUILD_TAG
v1.0.0
$ echo $CI_BUILD_REF
795db067ecfd3e848c683f6ff2e3de688b684b75
$ echo $CI_BUILD_REF_NAME
v1.0.0
$ git branch
* (detached from 795db06)
  master
$ git branch --contains $CI_BUILD_REF
* (detached from 795db06)
$ grep -q "master" <<< $(git branch --contains $CI_BUILD_REF) && test "$CI_BUILD_TAG" = "$CI_BUILD_REF_NAME" && npm publish || echo "Skipping because tag $CI_BUILD_TAG is not in master branch"
Skipping because tag v1.0.0 is not in master branch
```
My config:

```yaml
image: node:6.9

stages:
  - test
  - publish

npm_test:
  stage: test
  script:
    - npm install
    - npm test

publish:
  stage: publish
  script:
    - echo $CI_BUILD_TAG
    - echo $CI_BUILD_REF
    - echo $CI_BUILD_REF_NAME
    - git branch
    - git branch --contains $CI_BUILD_REF
    - grep -q "master" <<< $(git branch --contains $CI_BUILD_REF) &&
        test "$CI_BUILD_TAG" = "$CI_BUILD_REF_NAME" &&
        npm publish ||
        echo "Skipping because tag $CI_BUILD_TAG is not in master branch"
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
```

It looks git repo refs are not updated?

**Comment by alleus** [comment]
@plitex I did some refactoring of my solution, and this now works correctly for me:

* For regular commits, not on `develop` or `master`, will build and test my code
* For tags, conforming to [semver.org](http://semver.org), on the `master` branch, will deploy to production
* For tags, conforming to [semver.org](http://semver.org), on any other branch than `master`, will deploy to stage

```
Build:
  script:
    - echo "Build and test code without deploy"
  stage: build
  only:
    - branches
  except:
    - develop
    - master
Release:
  script:
    - grep -q "master" <<< $(git branch --contains $CI_BUILD_REF) && echo "On master branch, build and deploy to production"
    - grep -q "master" <<< $(git branch --contains $CI_BUILD_REF) || echo "NOT on master branch, build and deploy to stage"
  stage: deploy
  only:
    - /^v?[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-.]+)?\((?:\d+\))$/
```

**Comment by batazor** [comment]
My version is as follows:

**tag** `X.Y.Z.P` and `X.Y.Z` for **production**
**tag** `X.Y.Z-rcN` for **testing**

Example for `testing`:
```
build_testing:
  type: build
  script:
  - echo 'build_testing'
  only:
  - /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)-rc(?:0|[1-9]\d*)$/
  except:
  - branches
  when: on_success
```

Example for `production`:
```
build_production:
  type: build
  script:
  - echo 'build_production'
  only:
  - /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.?(?:0|[1-9]\d*)?$/
  except:
  - branches
  when: on_success
```
