### ISSUE TITLE
Gitlab doesn't trigger builds

### ISSUE THREAD

**Issue by kerberjg** [gitlabhq/gitlab-ci#643]
Recently I've been migrating some repos from other Gitlab CE instances to a new one, on a separate server. The culprit version of Gitlab CE is 8.6.5.

The project contains the following .gitlab-ci.yml :
```
stages:
  - deploy
  
production:
  type: deploy
  script:
  - forever stopall
  - npm install -d
  - forever start app.js
  only:
  - master
```

I'm sure the runner is configured correctly, as it keeps calling the Gitlab CE instance which results with the following logs:
in `gitlab-ctl tails`:
```
==> /var/log/gitlab/nginx/gitlab_access.log <==
127.0.0.1 - - [09/Apr/2016:15:20:29 +0200] "POST /ci/api/v1/builds/register.json HTTP/1.1" 404 58 "-" "Go-http-client/1.1"
````
and in `gitlab-runner --debug run` :
```
Feeding runners to channel                          builds=0
Checking for builds... nothing                      runner=*OMITTED*
```

I'm actually wondering if gitlabhq/gitlabhq#10127 is at fault somehow
