### ISSUE TITLE
GitLab CI ignores except: triggers

### ISSUE THREAD

**Issue by mykyta-protsenko** [gitlabhq/gitlab-ci#644]
I have a .gitlab-ci.yaml that has a build job that looks like this:

```
build:
  stage: build
  except:
    - triggers
  tags:
    - java
    - gradle
  script:
    - ./gradlew build
```

However, when I trigger the build through REST API (to execute other jobs), the build job (and other jobs with "except: triggers" option configured) are still executed.

I am running GitLab Community Edition 8.5.7 (72913ed).

Can you please look into this? Thanks!
