### ISSUE TITLE
Question to the workflow

### ISSUE THREAD

**Issue by bh** [gitlabhq/gitlab-ci#652]
Hi, have have the following `.gitlab-ci.yml`:

``` yaml
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ls

test:
  stage: test
  script:
    - function foo { return false; }
    - foo

deploy:
  stage: deploy
  when: manual
  script:
    - ls
```
How can I disable the manual action (`deploy`) to be triggered by an user if the previous job (`test`) was failed?
I think it should not be possible to do manual actions if a previous job was failed.

Thank you.
