### ISSUE TITLE
gitlab-ci does not work well with Windows virtual environments

### ISSUE THREAD

**Issue by newlog** [gitlabhq/gitlab-ci#658]
Hi there,

I'm not completely sure this issue should be addressed by gitlab-ci or virtualenv. So bear with me...

My use case is the following. I use gitlab-ci through a a Windows "shell" runner. The test stage creates a virtual environment and then executes the tests.

The issue is that regardless of the outcome of the tests, gitlab-ci sets the outcome to "passed". My theory is that when the Windows virtualenv is activated through the `activate.bat`, the output is set to off (`@echo off`). I'm not completely sure if that is supposed to screw results, but what I know for sure is that after activating the virtualenv no output is shown in the gitlab-ci website logs.

I fixed the issue by simulating the activation of the virtualenv manually from the gitlab-ci yml file. Basically, the only thing that is done when you activate a Windows virtualenv is prepending <venv_path>\Scripts to the environment PATH environment variable. This is the main reason that makes me suspect regarding that `@echo off`

Here you can see a non-working `gitlab-ci.yml` file. If you used it, you wouldn't see any output after the activate.bat, until the `after_script` where you would see what commands are being executed.

```
windows_tests:
   before_script:
     - set PYTHONPATH=%PYTHONPATH%;%CD%
     - virtualenv venv
   script:
     - venv\Scripts\activate.bat
     - pip install -r requirements.txt
     - py.test -k "test_windows_ or test_allplatforms"
   after_script:
     - rmdir /s /q venv
   tags:
     - windows
```

Here you can see the workarounds you have to do to avoid the aforementioned issue:

```
windows_tests:
  before_script:
    - set PYTHONPATH=%PYTHONPATH%;%CD%
    - set PYTHONHOME=
    - set PATH=%CD%\venv\Scripts;%PATH%
    - virtualenv venv
    - pip install -r requirements.txt
  script:
    - py.test -k "test_windows_ or test_allplatforms" --ignore=venv
  after_script:
    - rmdir /s /q venv
  tags:
    - windows
```

In linux, this doesn't appear to be an issue, there's a lot of people writing about how virtualenvs are used along with gitlab-ci, nevertheless you won't find any reference regarding Windows.

I just wanted to let you know.
